export const SELECT_ALBUM = 'SELECT_ALBUM';
export const TRIGGER_ALBUM_SEARCH = 'TRIGGER_ALBUM_SEARCH';
export const SEARCHING_ALBUMS = "SEARCHING_ALBUMS";
export const SEARCH_ALBUMS = "SEARCH_ALBUMS";
export const SEARCH_ALBUMS_SUCCESS = "SEARCH_ALBUMS_SUCCESS";
export const SEARCH_ALBUMS_FAILURE = "SEARCH_ALBUMS_FAILURE";